### PR TITLE
Bug/add pagination to operations

### LINKED ISSUE #92: Bug: No paging support
# 💬 Description

Currently none of our commands support paging.

# 🦶 Reproduction Steps

Steps to reproduce the behavior, provide an example of the command line issued:
1. Run a command on a dataset that exceeds the default page limit.

# 🤔 Expected Results

That all pages of data are fetched.

# 😲 Actual Results

On the first page of data is fetched.

### PR DESCRIPTION
**Pull request by DechengMa**
Closes #92 

# 📝 Summary of Changes

Changes proposed in this pull request:

Add pagination to 

- [x] List BundleIds
- [x] List Devices (in #181)
- [x] List Certificates
- [ ] List Profiles (not support by SDK yet)
- TestFlight
  - [x] List Apps
  - [x] List Beta Groups
  - [x] List Beta Testers
  - [x] List Builds
  - [x] List PreRelease Versions
- Users
  - [x] List Invitations (in #184)
  - [ ] List Visible Apps (may not be in 0.1.0)
  - [x] List Users 

# 🧐🗒 Reviewer Notes
Please point out if there are any operations that need pagination, if there are not included in this PR :)

### Problems:
This might break command line option:`--limit`. Can do some validation for option.limit is nil or not, then determine if pagination should be done or not.

## 🔨 How To Test

`swift run asc certificates list `
`swift run asc testflight prereleaseversion list`
`swift run asc users list`

### CODE REVIEW

**Comment by orj** [comment]
@DechengMa I think the full list of paginated responses is:
- List BundleIds
- List Devices
- List Certificates (done in this PR)
- List Profiles
- TestFlight
  - List Apps
  - List Beta Groups
  - List Beta Testers
  - List Builds (done previously?)
  - List PreRelease Versions (done in this PR)
- Users
  - List Invitations
  - List Visible Apps
  - List Users (done in this PR)

**Comment by orj** [comment]
@DechengMa please make sure pagination is applied to all the places it makes sense before closing #92

File: Sources/AppStoreConnectCLI/Services/Operations/ListCertificatesOpertaion.swift [hunk 1]
```diff
@@ -18,11 +20,7 @@ struct ListCertificatesOperation: APIOperation {
         }
     }
 
-    private let endpoint: APIEndpoint<CertificatesResponse>
-
-    init(options: ListCertificatesOptions) {
-        typealias Filter = Certificates.Filter
-
+    var filters: [Certificates.Filter] {
```
Comment (orj) [inline Sources/AppStoreConnectCLI/Services/Operations/ListCertificatesOpertaion.swift:23]:
```suggestion
    var filters: [Filter] {
```

File: Sources/AppStoreConnectCLI/Services/Operations/ListUsersOperation.swift [hunk 2]
```diff
@@ -6,42 +6,51 @@ import struct Model.User
...
 
-    init(options: ListUsersOptions) {
-        let include = options.includeVisibleApps ? [ListUsers.Include.visibleApps] : nil
-
-        let limit = [
-            options.limitUsers.map(ListUsers.Limit.users),
-            options.limitVisibleApps.map(ListUsers.Limit.visibleApps)]
-            .compactMap { $0 }
-            .nilIfEmpty()
+    var limit: [ListUsers.Limit]? {
```
Comment (orj) [inline Sources/AppStoreConnectCLI/Services/Operations/ListUsersOperation.swift:12]: Why not use the typealias?
```suggestion
    var limit: [Limit]? {
```

File: Sources/AppStoreConnectCLI/Services/Operations/ListAppsOperation.swift [hunk 3]
```diff
@@ -32,7 +21,27 @@ struct ListAppsOperation: APIOperation {
     typealias App = AppStoreConnect_Swift_SDK.App
 
     func execute(with requestor: EndpointRequestor) -> AnyPublisher<[App], Error> {
-        requestor.request(options.endpoint).map(\.data).eraseToAnyPublisher()
+        var filters: [ListApps.Filter] = []
+
+        options.bundleIds.isEmpty ? () : filters.append(.bundleId(options.bundleIds))
```
Comment (orj) [inline Sources/AppStoreConnectCLI/Services/Operations/ListAppsOperation.swift:26]: 🤔 Ok, so this is cute.  But I'm not sure I'm a fan of it.  Generally I'd suggest that ternary operators shouldn't be used for side effects.

```suggestion
        if options.bundleIds.isNotEmpty { filters.append(.bundleId(options.bundleIds)) }
```
This would require:
```
extension Collection {
    var isNotEmpty: Bool { isEmpty == false }
}
``` 
to be defined somewhere in the project. Or alternatively:
```suggestion
        if !options.bundleIds.isEmpty { filters.append(.bundleId(options.bundleIds)) }
```

But we tend to want to avoid the `!` not operator.

File: Sources/AppStoreConnectCLI/Services/Operations/ListBundleIdsOperation.swift [hunk 4]
```diff
@@ -33,6 +21,24 @@ struct ListBundleIdsOperation: APIOperation {
     typealias BundleId = AppStoreConnect_Swift_SDK.BundleId
 
     func execute(with requestor: EndpointRequestor) throws -> AnyPublisher<[BundleId], Error> {
-        requestor.request(options.endpoint).map(\.data).eraseToAnyPublisher()
+        let platforms = options.platforms.compactMap(Platform.init(rawValue:))
+
+        var filters: [BundleIds.Filter] = []
+        filters += options.identifiers.isEmpty ? [] : [.identifier(options.identifiers)]
```
Comment (orj) [inline Sources/AppStoreConnectCLI/Services/Operations/ListBundleIdsOperation.swift:27]: We should pick one way of doing this.  This is less "cute" than the alternative above. But then avoiding "cute"/"smart"/"tricky" code is preferred.
