### PR TITLE
Bug/Fix list beta tester group name not unique 

### LINKED ISSUE #168: Bug: testflight betatesters list --filter-group-names XYZ fails with Error: The group name you input ["XYZ"] are not unique.
# 🌎 Environment

 - OS: macOS
 - Version/Release: master as of 7c7ecb554af1810a59501212828fb8ef8029ddca

# 💬 Description

If you have a list of beta groups across apps or within an app that share the same substring you can not filter by that substring.

# 🦶 Reproduction Steps

With Beta Groups configured as:

App 1 Group Names: "XYZ", "ABCXYZ"
App 2 Group Names: "XYZ"

When you:
1. `./asc testflight betatesters list --filter-group-names "XYZ"`

# 🤔 Expected Results

That the beta testers for any group that matches "XYZ".

# 😲 Actual Results

The following error:

```
Error: The group name you input ["XYZ"] are not unique.
```

### PR DESCRIPTION
**Pull request by DechengMa**
Closes #168 
No can input a group name which might also be a substring of another group, two groups will be displayed together.

# 📝 Summary of Changes

Changes proposed in this pull request:

- Remove old `func betaGroupIdentifier`, migrate to operations.
- Use list beta group operations for getting multiple groups from one name.

# 🧐🗒 Reviewer Notes

##### Usage:
`swift run asc testflight betatesters list --filter-group-names yourGroupName`

## 🔨 How To Test

`swift run asc testflight betatesters list --filter-group-names yourGroupName`

### CODE REVIEW

File: Sources/AppStoreConnectCLI/Model/BetaGroup.swift [hunk 1]
```diff
@@ -57,44 +57,3 @@ extension BetaGroup {
         )
     }
 }
-
-extension AppStoreConnectService {
```
Comment (adamjcampbell) [inline Sources/AppStoreConnectCLI/Model/BetaGroup.swift:61]: Nice cleanup 😄
